### ISSUE TITLE
Discussion: Providing GLSL Transitions to Movie Editors

### ISSUE THREAD

**Issue by gre** [glslio/transitions.glsl.io#56]
One of the goal of GLSL.io is to provide transitions for Video Editors.

**from @rectalogic :**

> The goal of rendermix was to implement a video mixer using GLSL shaders to implement transitions/effects. This is also what it's precursor [WebVfx](http://rectalogic.github.io/webvfx/) does - WebVfx allows you to write transitions/filters/effects using WebGL and use those in a video processing pipeline as an [MLT](www.mltframework.org) plugin. WebVfx is based on [QtWebKit](https://trac.webkit.org/wiki/QtWebKit), but you need a version built to enable WebGL. QtWebKit has been [abandoned](http://blog.qt.digia.com/blog/2013/09/12/introducing-the-qt-webengine/) and the replacement QWebEngine will not have the features WebVfx requires.
> 
> So I wrote [v8-webgl](https://github.com/rectalogic/v8-webgl) - a partial implementation of WebGL using desktop OpenGL and the v8 JavaScript engine, along with  [ANGLE](https://code.google.com/p/angleproject/) to translate the WebGL glsl shaders to desktop OpenGL - independent of a web browser and designed to be used as a video editor plugin. Then I wrote rendermix (based on the jMonkeyEngine videogame engine), and some others as attempted replacements.
> 
> All that said, I think the most straightforward way to make glsl.io work with video editors is to write a [frei0r](http://www.dyne.org/software/frei0r/) plugin. ffmpeg, mlt and [others](http://en.wikipedia.org/wiki/Frei0r#Applications_which_use_frei0r) all already support frei0r. I think the plugin would need to use ANGLE to translate the WebGL GLSL transition shader to OpenGL GLSL.
> 
> So basically a frei0r mixer2 or mixer3 plugin that would initialize an OpenGL context, convert the transition glsl from WebGL to OpenGL using ANGLE and compile the shader program, then in [f0r_update2](http://frei0r.dyne.org/codedoc/html/frei0r_8h.html#a5c0f4d80066aeedc695732c6f929183d) upload the image bits for each frame with glTexImage2D, run the shader program, download the resulting bits using glReadPixels and set those in the f0r_update2 outframe argument.

**Comment by gre** [comment]
Just a little :up:

A few people are requesting this feature. This is not an easy task to implementing. But it would be incredible for GLSL Transitions ecosystem to grow.

**Comment by transitive-bullshit** [comment]
@gre @rectalogic I needed this functionality for a project, so I decided to implement it as a new ffmpeg filter.  You can check out the source [here](https://github.com/transitive-bullshit/ffmpeg-gl-transition) -- would love to hear your thoughts!

I'm not transpiling the shader source via ANGLE yet because ANGLE seems like a beast.  I'm also not sure it's necessary, as webgl glsl appears to be stricter than desktop glsl and the gl-transitions I've tested with have all worked so far.

**Comment by gre** [comment]
@transitive-bullshit this is awesome!!!
